export enum TipoVisualizacaoEnum {
  CRIADO = 1,
  RECEBIDO = 2,
  ENVIADO = 3,
  INSTITUICAO_EXTERNA = 4,
  DISTRIBUICAO_RECEBIDO = 5,
  DISTRIBUICAO_ENVIADO = 6,
  PETICIONAMENTO_ABERTO = 7,
  PETICIONAMENTO_CONCLUIDO = 8,
}
