export const TEXTO_TEMPLATE = `Ao utilizar as tags abaixo é possível utilizar valores padrões: como usuário logado, órgão e setor no qual pertence.\n
As tags vão ser substituídas pelos valores correspondentes quando o template for utilizado.`;

interface EditorConfig {
  [key: string]: string[] | string | number;
}

export const EDITORCONFIG: EditorConfig = {
  toolbar: [
    'fontSize',
    '|',
    'bold',
    'italic',
    'strikethrough',
    'underline',
    '|',
    'link',
    'insertTable',
    '|',
    'bulletedList',
    'numberedList',
    '|',
    'alignment',
  ],
  language: 'pt-br',
};

export const TRADUCAOCONFIG: EditorConfig = {
  startsWith: 'Começa com',
  contains: 'Contém',
  notContains: 'Não contém',
  endsWith: 'Termina com',
  equals: 'Igual a',
  notEquals: 'Diferente de',
  noFilter: 'Sem filtro',
  lt: 'Menor que',
  lte: 'Menor que ou igual a',
  gt: 'Maior que',
  gte: 'Maior que ou igual a',
  is: 'é',
  isNot: 'não é',
  before: 'Antes',
  after: 'Depois',
  dateIs: 'Data é',
  dateIsNot: 'Data não é',
  dateBefore: 'Data é antes de',
  dateAfter: 'Data é depois de',
  clear: 'Limpar',
  apply: 'Aplicar',
  matchAll: 'Relacionar Todos',
  matchAny: 'Relacionar Qualquer',
  addRule: 'Adicionar Regra',
  removeRule: 'Remover Regra',
  accept: 'Sim',
  reject: 'Não',
  choose: 'Escolher',
  upload: 'Upload',
  cancel: 'Cancelar',
  dayNames: [
    'Domingo',
    'Segunda',
    'Terça',
    'Quarta',
    'Quinta',
    'Sexta',
    'Sabado',
  ],
  dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sab'],
  dayNamesMin: ['Do', 'Sg', 'Te', 'Qa', 'Qi', 'Sx', 'Sa'],
  monthNames: [
    'Janeiro',
    'Fevereiro',
    'Março',
    'Abril',
    'Maio',
    'Junho',
    'Julho',
    'Agosto',
    'Setembro',
    'Outubro',
    'Novembro',
    'Dezembro',
  ],
  monthNamesShort: [
    'Jan',
    'Fev',
    'Mar',
    'Abr',
    'Mai',
    'Jun',
    'Jul',
    'Ago',
    'Set',
    'Out',
    'Nov',
    'Dez',
  ],
  dateFormat: 'mm/dd/yy',
  firstDayOfWeek: 0,
  today: 'Hoje',
  weekHeader: 'Wk',
  weak: 'Weak',
  medium: 'Medium',
  strong: 'Strong',
  passwordPrompt: 'Coloque uma senha',
  emptyMessage: 'Nenhum resultado encontrado',
  emptyFilterMessage: 'Nenhum resultado encontrado',
};
